### ISSUE TITLE
Marketplace Documentation

### ISSUE THREAD

**Issue by lukerollans** [tigris/pin_payment#10]
It would be super awesome if README could be updated with some Marketplace API examples. Happy to donate if you can get around to this.

Cheers, and thanks for the gem!

**Comment by lukerollans** [comment]
@Ruxton any change on this mate?

**Comment by lukerollans** [comment]
PS: I meant to type "any chance" on this, not "any change". The latter must of come off as quite rude

**Comment by Ruxton** [comment]
sure thing, I can write some examples up once I'm done working on the implementation I'm doing.

**Comment by lukerollans** [comment]
Awesome, cheers. I'm sure I can figure it out from the source, but documentation would still be sweet. PS: I'm a mate of Carl Clarke's, he said hi! Thought your name was familiar, pretty sure we've played BF3 in the past
